#!/bin/bash
#-----------------------
# Testing cinder-daemons
#-----------------------
set -e
DAEMONS=('cinder-api' 'cinder-scheduler')

for daemon in "${DAEMONS[@]}"; do
    if pidof -x $daemon > /dev/null; then
        echo "OK"
    else
        echo "ERROR: ${daemon} IS NOT RUNNING"
        exit 1
    fi
done
