..
    Warning: Do not edit this file. It is automatically generated from the
    software project's code and your changes will be overwritten.

    The tool to generate this file lives in openstack-doc-tools repository.

    Please make any changes needed in the code, then run the
    autogenerate-config-doc tool from the openstack-doc-tools repository, or
    ask for help on the documentation mailing list, IRC channel or meeting.

.. _cinder-scality:

.. list-table:: Description of Scality SOFS volume driver configuration options
   :header-rows: 1
   :class: config-ref-table

   * - Configuration option = Default value
     - Description
   * - **[DEFAULT]**
     -
   * - ``scality_sofs_config`` = ``None``
     - (String) Path or URL to Scality SOFS configuration file
   * - ``scality_sofs_mount_point`` = ``$state_path/scality``
     - (String) Base dir where Scality SOFS shall be mounted
   * - ``scality_sofs_volume_dir`` = ``cinder/volumes``
     - (String) Path from Scality SOFS root to volume dir
