..
    Warning: Do not edit this file. It is automatically generated from the
    software project's code and your changes will be overwritten.

    The tool to generate this file lives in openstack-doc-tools repository.

    Please make any changes needed in the code, then run the
    autogenerate-config-doc tool from the openstack-doc-tools repository, or
    ask for help on the documentation mailing list, IRC channel or meeting.

.. _cinder-nimble:

.. list-table:: Description of Nimble driver configuration options
   :header-rows: 1
   :class: config-ref-table

   * - Configuration option = Default value
     - Description
   * - **[DEFAULT]**
     -
   * - ``nimble_pool_name`` = ``default``
     - (String) Nimble Controller pool name
   * - ``nimble_subnet_label`` = ``*``
     - (String) Nimble Subnet Label
   * - ``nimble_verify_cert_path`` = ``None``
     - (String) Path to Nimble Array SSL certificate
   * - ``nimble_verify_certificate`` = ``False``
     - (String) Whether to verify Nimble SSL Certificate
