..
    Warning: Do not edit this file. It is automatically generated from the
    software project's code and your changes will be overwritten.

    The tool to generate this file lives in openstack-doc-tools repository.

    Please make any changes needed in the code, then run the
    autogenerate-config-doc tool from the openstack-doc-tools repository, or
    ask for help on the documentation mailing list, IRC channel or meeting.

.. _cinder-zte:

.. list-table:: Description of Zte volume driver configuration options
   :header-rows: 1
   :class: config-ref-table

   * - Configuration option = Default value
     - Description
   * - **[DEFAULT]**
     -
   * - ``zteAheadReadSize`` = ``8``
     - (Integer) Cache readahead size.
   * - ``zteCachePolicy`` = ``1``
     - (Integer) Cache policy. 0, Write Back; 1, Write Through.
   * - ``zteChunkSize`` = ``4``
     - (Integer) Virtual block size of pool. Unit : KB. Valid value : 4, 8, 16, 32, 64, 128, 256, 512.
   * - ``zteControllerIP0`` = ``None``
     - (IP) Main controller IP.
   * - ``zteControllerIP1`` = ``None``
     - (IP) Slave controller IP.
   * - ``zteLocalIP`` = ``None``
     - (IP) Local IP.
   * - ``ztePoolVoAllocatedPolicy`` = ``0``
     - (Integer) Pool volume allocated policy. 0, Auto; 1, High Performance Tier First; 2, Performance Tier First; 3, Capacity Tier First.
   * - ``ztePoolVolAlarmStopAllocatedFlag`` = ``0``
     - (Integer) Pool volume alarm stop allocated flag.
   * - ``ztePoolVolAlarmThreshold`` = ``0``
     - (Integer) Pool volume alarm threshold. [0, 100]
   * - ``ztePoolVolInitAllocatedCapacity`` = ``0``
     - (Integer) Pool volume init allocated Capacity.Unit : KB.
   * - ``ztePoolVolIsThin`` = ``False``
     - (Integer) Whether it is a thin volume.
   * - ``ztePoolVolMovePolicy`` = ``0``
     - (Integer) Pool volume move policy.0, Auto; 1, Highest Available; 2, Lowest Available; 3, No Relocation.
   * - ``zteSSDCacheSwitch`` = ``1``
     - (Integer) SSD cache switch. 0, OFF; 1, ON.
   * - ``zteStoragePool`` =
     - (List) Pool name list.
   * - ``zteUserName`` = ``None``
     - (String) User name.
   * - ``zteUserPassword`` = ``None``
     - (String) User password.
