.. _cinder-swift:

.. list-table:: Description of swift configuration options
   :header-rows: 1
   :class: config-ref-table

   * - Configuration option = Default value
     - Description
   * - **[DEFAULT]**
     -
   * - ``backup_swift_auth_insecure`` = ``False``
     - (Boolean) Bypass verification of server certificate when making SSL connection to Swift.
   * - ``backup_swift_auth_url`` = ``None``
     - (URI) The URL of the Keystone endpoint
